/**
 * Locked scaffold for the next-tailwind-ts stack.
 *
 * These files are always generated from here — the LLM never touches them.
 * __SITE_TITLE__ in layout.tsx is substituted at runtime.
 */

const PACKAGE_JSON = `{
  "name": "ai-site",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "typescript": "latest",
    "@types/node": "latest",
    "@types/react": "latest",
    "tailwindcss": "latest",
    "postcss": "latest",
    "autoprefixer": "latest",
    "eslint": "latest",
    "eslint-config-next": "latest"
  }
}
`;

const TSCONFIG = `{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;

const TAILWIND_CONFIG = `import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
} satisfies Config;
`;

const POSTCSS_CONFIG = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

const GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

const LAYOUT_TSX = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "__SITE_TITLE__",
  description: "Generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

const GITIGNORE = `/node_modules
/.pnp
.pnp.js
.yarn/install-state.gz
/coverage
/.next/
/out/
/build
.DS_Store
*.pem
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.env*.local
.vercel
*.tsbuildinfo
next-env.d.ts
`;

type ScaffoldFile = { path: string; content: string };

const BASE_SCAFFOLD: ScaffoldFile[] = [
  { path: "package.json",       content: PACKAGE_JSON },
  { path: "tsconfig.json",      content: TSCONFIG },
  { path: "next.config.mjs",    content: NEXT_CONFIG },
  { path: "tailwind.config.ts", content: TAILWIND_CONFIG },
  { path: "postcss.config.js",  content: POSTCSS_CONFIG },
  { path: "app/globals.css",    content: GLOBALS_CSS },
  { path: "app/layout.tsx",     content: LAYOUT_TSX },
  { path: ".gitignore",         content: GITIGNORE },
];

/** Returns scaffold files with __SITE_TITLE__ substituted in layout.tsx. */
export function getScaffoldFiles(siteTitle: string): ScaffoldFile[] {
  return BASE_SCAFFOLD.map((f) => ({
    ...f,
    content: f.content.replace(/__SITE_TITLE__/g, siteTitle),
  }));
}

/** Scaffold file paths — LLM output matching these is silently dropped. */
export const SCAFFOLD_PATHS = new Set(BASE_SCAFFOLD.map((f) => f.path));
